/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world. 2222";
    }

    public static void main(String[] args) {
        System.out.println(new App());
    }

    public String toString(){
        return "APP";
    }


}
